USE [master]
GO

/****** Object:  Database [energy]    Script Date: 04.02.2016 21:03:55 ******/
CREATE DATABASE [energy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'energy', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\energy.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'energy_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\energy_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [energy] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [energy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [energy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [energy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [energy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [energy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [energy] SET ARITHABORT OFF 
GO

ALTER DATABASE [energy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [energy] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [energy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [energy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [energy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [energy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [energy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [energy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [energy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [energy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [energy] SET  DISABLE_BROKER 
GO

ALTER DATABASE [energy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [energy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [energy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [energy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [energy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [energy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [energy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [energy] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [energy] SET  MULTI_USER 
GO

ALTER DATABASE [energy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [energy] SET DB_CHAINING OFF 
GO

ALTER DATABASE [energy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [energy] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [energy] SET  READ_WRITE 
GO

